### ISSUE TITLE
double_float digits, digits10 and max_digits10 numeric limits

### ISSUE THREAD

**Issue by ckormanyos** [BoostGSoC21/multiprecision#21]
Hi @sinandredemption and @cosurgi there are a few scattered mentions in other issues regarding this.

In this issue, we ponder the proper valued for the `digits`, `digits10` and `max_digits10` for `std::numeric_limits<double_float<T>>`.

**Comment by ckormanyos** [comment]
I do not know or remember exactly when or where I encountered this. But I believe I recall an early, original work of _double-double_ from a developer Briggs. He claimed that the `digits` parameter for double-double was, I believe, 104. That case corresponds to the `digits` parameter for our `double_float<double>`.

So what I do not exactly understand is why it is twice the value of one less than the digits parameter of the constituent part. If this is, in fact, the rule, then we would have:

```
std::numeric_limits<double_float<T>>::digits = 2 * (std::numeric_limits<T>::digits - 1)
```

For 8-byte `double`, this corresponds to
<img src="https://render.githubusercontent.com/render/math?math=d_{2}\,=\,2\,\times\,52\,=\,104">. For 4-byte `float`, then we would have
<img src="https://render.githubusercontent.com/render/math?math=d_{2}\,=\,2\,\times\,23\,=\,46">.

I do not know if that formula is exactly correct, nor do I understand why we would lose _two_ of the underlying binary digits.

But following that, once you have the number of binary digits, you can use Kahan's formula for the number of decimal digits: <img src="https://render.githubusercontent.com/render/math?math=d_{10}\,=\,(d_{2} - 1)\,\times\,\log10\left(2\right)">.

**Comment by ckormanyos** [comment]
The post above would theoretically give us values for the `digits` and the `digits10` parameter.

To obtain the `max_digits10` parameter, we might consider exploring some of the information at [exploring binary](https://www.exploringbinary.com/topics/)

**Comment by sinandredemption** [comment]
Hello @ckormanyos @cosurgi 

I'd request you to read [this detailed comment](https://github.com/BoostGSoC21/multiprecision/commit/803b96723ad39c785b954375c0e56fbf81d5d784#commitcomment-53591647) (in case you haven't read already) where I discuss this issue in detail and justify my choice for values of digits, digits10, max_exponent etc.

We will also need to update `std::numeric_limits<cpp_double_float<FloatingPointType>>::max/min` accordingly.

EDIT: I have made [an additional comment](https://github.com/BoostGSoC21/multiprecision/commit/803b96723ad39c785b954375c0e56fbf81d5d784#commitcomment-53646736) on the commit. I should have posted it here instead.

Kind regards,
Fahad

**Comment by cosurgi** [comment]
> nor do I understand why we would lose two of the underlying binary digits.

`float`, `double`, `long double` and `float128` use 1 bit to store the sign, but only `float`, `double` and `float128` have an implicit first bit=1. The `long double` does not use the implicit bit. So let us try to calculate how many bits **really** a type has.

### Table 1
| Type                | sign  | exponent | fraction | implicit integer bit == 1 | significand | sum |
| ------------------- | ------ | ------------ | ---------- | --------------- | ------------ | --------- |
| float                | 1      | 8             | 23         | yes             | 24           | 1+8+23 = 32   |
| double            | 1       | 11           | 52         | yes             | 53           | 1+11+52 = 64 |
| long double     | 1       | 15          | 64         | no               | 64           | 1+15+64 = 80 |
| float128          | 1       | 15          | 112       | yes             | 113          | 1+15+112 = 128 |

When we construct double_float type from them we benefit from the implicit bit. Because, thanks to exponent, it is always guaranteed to be 1.

Let us try to construct similar table for double_float types. We know that exponent is "unimportant" in the sense that it is "sort-of duplicated" in each of the constituent parts. But please do verify this (please edit this post, even, so that we don't have mistakes luring here) as I might have made a mistake here or there.

### Table 2
| double_float<Type> | sign | exponent | fraction | implicit integer bit == 1 | significand | sum |
| -------------------------- | ------ | ------------ | ---------- | --------------- | -------------- | --------- |
| float                         | 1*2   | 8*2         | 23*2      | yes             | 24*2=48   | (1+8+23)*2 = 64   |
| double                     | 1*2   | 11*2        | 52*2      | yes             | 53*2=106 | (1+11+52)*2 = 128 |
| long double              | 1*2   | 15*2       | 64*2      | no               | 64*2=128 | (1+15+64)*2 = 160 |
| float128                   | 1*2   | 15*2       | 112*2    | yes             | 113*2=226 | (1+15+112)*2 = 256 |


So following this logic let's try to construct the answers to this issue:
Let us try to take the significand as the number of binary digits in the number, then use the Kahan's formula:

```
digits10     = trunc( (d2-1)*log10(2) );
max_digits10 = trunc( log10(2)*d2 )+2;
```

### Table 3
|              Type         | digits | digits10 | max_digits10 |
| ------------------------- | ------ | -------- | ------------ |
| float                     | 24     | 6        | 9            |
| double                    | 53     | 15       | 17           |
| long double               | 64     | 18       | 21           |
| float128                  | 113    | 33       | 36           |
| double_float\<float\>       | 48     | 14       | 16           |
| double_float\<double\>      | 106    | 31       | 33           |
| double_float\<long double\> | 128    | 38       | 40           |
| double_float\<float128\>    | 226    | 67       | 70           |

(I used `calc` from apcalc package with `define dig10(d2)=int( (d2-1)*log(2) )` and `define dig10max(d2)=int( log(2)*d2 )+2`)

I didn't compare the first four with `std::numeric_limits`. So there's still some work to be done here.

**EDIT:** added later. The same table as above but with a [simplified assumption](https://github.com/BoostGSoC21/multiprecision/issues/21#issuecomment-882093977): we don't use `bool carrier` to carry around the implicit bit == 1 in addition and in other operations. So only one implicit bit is allowed, the most significant one:

### Table 4
| Type, but at most use only one implicit bit | digits | digits10 | max_digits10 |
| ------------------------- | ------ | -------- | ------------ |
| float                     | 24     | 6        | 9            |
| double                    | 53     | 15       | 17           |
| long double               | 64     | 18       | 21           |
| float128                  | 113    | 33       | 36           |
| double_float\<float\>       | 47     | 13       | 16           |
| double_float\<double\>      | 105    | 31       | 33           |
| double_float\<long double\> | 128    | 38       | 40           |
| double_float\<float128\>    | 225    | 67       | 69           |

It is interesting to observe that the last four rows are strikingly similar to the table above. This is not a surprise, that's "just one bit" of a difference. We shall remember though, that the decimal numbers in the lower table are much more constrained in possible values than in the upper table. Just as much as the single bit does, the Table 3 has about 0.30102 more of decimal precision than Table 4.

I don't know how feasible is to implement the `bool carrier` bit. And we need to focus on quad_float, in which these three missing bits will amount to almost a single decimal digit. I know that having `bool carrier` will resolve many questions from the future users of quad_float asking: "Hey, double has 53 digits, so why quad_float doesn't have 212 digits?", but it also will make computations slower. So maybe we could defer this to some later time as a template specialization: slower calculations, three more bits (in quad) and one more bit (in double) :)

**Comment by cosurgi** [comment]
Thank you for bringing this up:

> I'd request you to read [this detailed comment](https://github.com/BoostGSoC21/multiprecision/commit/803b96723ad39c785b954375c0e56fbf81d5d784#commitcomment-53591647) (in case you haven't read already) where I discuss this issue in detail and justify my choice for values of digits, digits10, max_exponent etc.

> EDIT: I have made [an additional comment](https://github.com/BoostGSoC21/multiprecision/commit/803b96723ad39c785b954375c0e56fbf81d5d784#commitcomment-53646736) on the commit. I should have posted it here instead.

> This means, for example, cpp_double_float has actually only 104 bits of precision (unlike the theoretical 106 bits). I am not sure where the two bits of precision are lost to. + and - operators pass all tests with even when the min accuracy threshold is set at 105 bits (but not 106 bits). However, * and / operators fail the tests where min accuracy threshold is above 104 bits.

Now we can go back to my post above, and verify the calculations in there. I may have a mistake there, but I imagine that we have already identified where the two missing bits come from: these are the two implicit bits. One from each of the underlying type.

The debugging of this situation will be much simpler with `long double` because it does not use the implicit bit == 1.

**Comment by cosurgi** [comment]
Ahh, you have found the explanation:

> the second float of the internal representation of cpp_double_float<> is often subnormal. 

The subnormal numbers cannot benefit from the implicit bit==1. Their actual precision suddenly is one bit smaller. The fact that the number is subnormal is signaled via a reserved value of the exponent. So for subnormal numbers you should put in the table above one bit less in the `digits` column.

Things get funny if our quad_float<Type> becomes a sum of a regular and a subnormal number. I imagine that this is possible. And in such case the double_float<double> could for example have 53+52=105 digits. Which you have encountered.

**Comment by cosurgi** [comment]
As I am reading the rest of [your comment](https://github.com/BoostGSoC21/multiprecision/commit/803b96723ad39c785b954375c0e56fbf81d5d784) I don't know why it always fails when assuming 106 digits precision. I would expect it to fail only when one component is subnormal.

**Comment by cosurgi** [comment]
> To prevent this, max_exponent has been reduced so that the the second float is never subnormal, which can be guaranteed if the exponent of the first float is capped.

yes, this makes sense. Fewer troubles if we avoid subnormal.

Now I am starting to wonder, maybe the "middle" implicit bit==1 does not do the work which I am expecting that it is doing. But if so, then why? This would explain why only 105, but the reason, at present eludes me.

**Comment by cosurgi** [comment]
> At your request, I could also quickly make a new branch with the old std::numeric_limits specialization for the same purpose.

Maybe instead of a branch, you could put an `#idef BOOST_DEBUG_SUBNORMAL` or something like that in the work branch. This would help us to directly compare the affected lines of code.

**Comment by ckormanyos** [comment]
Great explanations @sinandredemption and @cosurgi ! Thanks for these.

I had created this issue as a reference.
The answers to this issue seem to be complete, especially with previous comments/commits from @sinandredemption.

If we are complete, then please I suggest to use these fine results in the specialization(s) of `std::numeric_limits<double_float<T>>`.

**Comment by cosurgi** [comment]
>  This would explain why only 105, but the reason, at present eludes me.

Ah! it is clear now: the implicit bit cannot participate in any of the arithmetic operations. For example addition needs a carrier bit to proceed with addition in the next part of the binary representation. But the implicit bit is sort of **mute**. It must be == 1. It cannot carry anything. So it cannot participate in the arithmetic operations. In multiplication this is especially important, because this **mute** bit would appear in more places.

I will update the tables above following this new logic: we can use only one implicit bit == 1. And that is the single most significant bit. All the implicit bits in the middle (we will have three of then in quad_float) only cause problems because they cannot participate in the calculations.

**Comment by cosurgi** [comment]
This made me realize that other path is possible: in the implementation of addition use an extra `bool carrier` which would carry the information of this **mute** bit. I am not sure if this is feasible though. Would be interesting to see if we could achieve 106 bits precision using such approach...

**Comment by sinandredemption** [comment]
> This made me realize that other path is possible

The [arithmetic tests](https://github.com/BoostGSoC21/multiprecision/blob/gsoc2021_double_float/test/test_cpp_double_float_arithmetic.cpp) are apparently robust and ready-to-use for such an experiment. I would be very interested in seeing the results, and possibly even coding it myself.

**Comment by cosurgi** [comment]
> The [arithmetic tests](https://github.com/BoostGSoC21/multiprecision/blob/gsoc2021_double_float/test/test_cpp_double_float_arithmetic.cpp) are apparently robust and ready-to-use for such an experiment. I would be very interested in seeing the results, and possibly even coding it myself.

@sinandredemption this is great! If you want to investigate this, then please by all means give it a try. EDIT: and in such case perhaps better to make this optional via bool template argument with some default value. As not everyone might want to have slower addition and 1 (or 3) more bits. EDIT2: if you will see that it takes too much time, then maybe better to skip it, for now.

@ckormanyos what would you say, we don't want to neglect quad_float, right?

**Comment by sinandredemption** [comment]
> and in such case perhaps better to make this optional via bool template argument with some default value

Exactly my line of thought.

> we don't want to neglect quad_float

This is my concern too, given the limited time left for the project (although I do plan to continue contribute to the project even after GSoC ends). Currently, I guess I would continue to work on quad_float, and put in a day or two into this experiment along the way. Meanwhile, in case you feel like coding it yourself, please go forward by all means.

**Comment by ckormanyos** [comment]
> what would you say, we don't want to neglect quad_float, right?

On the one hand, we did want to march steadily on toward `quad_float`. We do, however, admit that the community really will benefit from a clean, well-tested, robust Boost-licensed, free `double-double` replacement, as this has also been missing for a very, very long time.

In fact, we might go so far as to say that the main result of this entire project (within the limited scope of the GSoC '21) might or even could be a clean `double_float`.

On the other hand, the foundation for `double_float` has been established. And it _could_ make sense to leave just a few stones unturned on `double_float` and catch these in the form of open issues, thereby moving forward on `quad_float`.

All-in-all, my recommendation would be to:

- Get `double_float` close to a usable, testable form, also wrapped as a `number` backend for Boost.
- Make at least a draft for `quad_double` and identify possibly the best way to implement this artifact.

But I am open to favoring one or both, as per preference.

@cosurgi and @sinandredemption

**Comment by sinandredemption** [comment]
> We do, however, admit that the community really will benefit from a clean, well-tested, robust Boost-licensed, free double-double replacement, as this has also been missing for a very, very long time.

If case you are referring to David Bailey's QD package, please note that `cpp_double_float<>` arithmetic behavior is an **exact** replica of the QD package's `dd_real` class, along with it's limitations (104 bits only, trouble handling subnormals).

**Comment by cosurgi** [comment]
@ckormanyos this is a great advice. Let us allow @sinandredemption make the important decision here.

**Comment by cosurgi** [comment]
It's still possible that I made a mistake somewhere above.

However I am quite confident and `cpp_quad_float<long double>` could be very robust: no problems with implicit bits and plenty of precision.

EDIT: ehh. and I made a typo in the sentence above :) Corrected now :)

**Comment by sinandredemption** [comment]
@ckormanyos @cosurgi 

Thank you for your guidance. I think I'll move forward along these lines:

- experiment with `cpp_quad_float<>` via a simple `cpp_double_float<cpp_double_float<>>` cascade, and see if it passes all tests and works as expected
- if everything works fine, code the `eval_*` routines as required to fit in the Boost.Multiprecision convention
- Code the specializations for cpp_quad_float (e.g. multiplication routines)

Cheers,
Fahad

**Comment by ckormanyos** [comment]
> move forward along these lines...

Yes @sinandredemption, that seems like a really good plan!

**Comment by ckormanyos** [comment]
> compare the first four with `std::numeric_limits` ...

The first four agree with `std::numeric_limits` on well-known compilers.

Question @cosurgi since we are still getting some test failures from sporadic arithmetic operations when dealing with the precision. Do the considerations in the tables above give us insight into which tolerances should actually be set in the arithmetic tests? I wonder... if these test failures are simple failures to properly set the test tolerance(s)?

**Comment by cosurgi** [comment]
>  I wonder... if these test failures are simple failures to properly set the test tolerance(s)?

Please see #28, I am worried that it will be difficult to make it work without handling these implicit bits.

**Comment by ckormanyos** [comment]
> difficult to make it work without handling these implicit bits

Hi @cosurgi I still need to study up quite a bit on this topic. I wonder, however, what exactly do you mean with _make_ _it_ _work_ and also what does this mean for our algorithms in `double-float`?

I think you mean we need to handle the implicit bits as shown in the link to the work you provide. Is this correct?

Why do other packages (mentioned above QD or double-double) seem to neglect this as well?

**Comment by sinandredemption** [comment]
@ckormanyos Quick response on this:

> Why do other packages (mentioned above QD or double-double) seem to neglect this as well?

Could one explanation be a lack of testing for the extreme cases, since these cases don't seem to show up using standard uniform distribution of random numbers? In our test cases, we are using a specialized distribution where these extreme cases are actually very common.

**Comment by ckormanyos** [comment]
> these extreme cases

The cases don't seem that extreme to me. I would like to investigate further...

Here are two failing test cases I found, where the hexadecimal representations of the x,y components are the lo/hi parts of a `double_float<double>` on a system with `double` having 64 bits.

```
Testing correctness of arithmetic operators for class boost::multiprecision::backends::cpp_double_float<double>
testing operator* (accuracy = 104 bits)... [FAILED] while performing '2.608321316504839982942125975335e-16' * '3.815009345086551163470799753151e-16'
da_x: 0x3cb2cb80ea899289
da_y: 0x395e3c0000000000
db_x: 0x3cbb7d7339ef4371
db_y: 0x395fa00000000000

Testing correctness of arithmetic operators for class boost::multiprecision::backends::cpp_double_float<double>
testing operator* (accuracy = 104 bits)... [FAILED] while performing '3.246555228235691726172953098508e-16' * '1.714815675337499651066142477857e+201'
da_x: 0x3cb764d65c059b31
da_y: 0x395dac0000000000
db_x: 0x69b6671736e730d7
db_y: 0x665c077fd297e000
```

**Comment by cosurgi** [comment]
Maybe the problems discovered by @sinandredemption with the last bit are also exposed in this loop condition: `while (norm != 0) {` because that loop is taking away exactly one non-zero bit `norm -= static_cast<Rr>(0.5);` in each loop execution. This loop is fairly simple, and it works with all other multiprecision types that I ever tested (MPFR, cpp_bin_float, and others). However in this case with double float it has some problems.

I did not nail down exactly why this loop cannot reach `norm == 0` after taking away all the bits from the number. It is likely to be connected with the other problems that we are experiencing here.

But it is also possible that my extremely rudimentary implementations of `pow` and `frexp` in there have some hidden bug. (I have one uncommited “fix” of `frexp`, where it adds 0.5 or subtracts 0.5 if the number after construction of quad double is not in the range of the BOOST_ASSERTs that follow it.)

The very simple number to debug with is mentioned in the title of last commit there "0.74981689453125", it has simple binary representation 10111111111101 with exponent -1 and yet it fails.

Overall I see two solutions right now, before nailing the exact problem with this loop `while (norm != 0) {` :

1. handle implicit bits in + - / * , but that will be some extra work
2. find some other way to make it consistent in + - / * by reducing the number of used bits and zeroing the extra ones.

Maybe something else. I feel that either of these solutions will take more time than we planned. So maybe better to let this bug sit here for a while, when we keep thinking about it, and focus on quad double instead. It is rather certain that the solution will be the same in both cases, and we might gain extra insight by seeing how this problem evolved in quad double.

**Comment by cosurgi** [comment]
Ahh, I forgot about one important thing: the failures are happening even in `long double`, which means that it’s not only the implicit bit to blame, since `long double` doesn’t have it.

**Comment by cosurgi** [comment]
Maybe it has got something to do with the normalization of a number, since the number tends to turn from:
```
01000000
```
into
```
00111111
```

**Comment by cosurgi** [comment]
Ah, in that context the _make_ _it_ _work_ meant feeding 10000 of random numbers into https://github.com/BoostGSoC21/multiprecision/pull/28/files#diff-8ce98636352ad37d2f0d1f88c11d031b89c5ca520570fa2db2f5ff520587ddeaR160

**Comment by ckormanyos** [comment]
> ... either of these solutions will take more time than we planned. So maybe better to let this bug sit here for a while, when we keep thinking about it, and focus on quad double instead ...

Totally agree.

@sinandredemption what do you think?

We could do a little bit more wrap up of `double_float` as a Boost.Multiprecision backend. Maybe improve `frexp`, `ldexp`, `floor`, `ceil`, `sqrt` along the way, as these are, I believe mandatory for the backend. Then move on to `quad_float`...

**Comment by sinandredemption** [comment]
> @sinandredemption what do you think?

@ckormanyos How about this plan: I create a new branch and do some preliminary work related to quad-float, and meanwhile you and @cosurgi continue to work on `cpp_double_float` (bugs or other things, as you please). And after I get some basic tests running (arithmetic, constructors etc), I join the both of you again to work on the known issues and start developing other things (Boost.Multiprecision backend, c-style math functions).

Please let me know what you think, especially whether starting to work on cpp_quad_float before taking care Boost.Multiprecision backend would be a good idea.

**Comment by ckormanyos** [comment]
> @ckormanyos How about this plan: I create a new branch and do some preliminary work related to quad-float, and meanwhile you and @cosurgi continue to work on cpp_double_float (bugs or other things, as you please). And after I get some basic tests running (arithmetic, constructors etc), I join the both of you again to work on the known issues and start developing other things (Boost.Multiprecision backend, c-style math functions).

This seems perfect to me.

> Please let me know what you think, especially whether starting to work on cpp_quad_float before taking care Boost.Multiprecision backend would be a good idea.

Yes. Agreed. This plays to your strengths. Please feel free to try out a few things in an open/non-Boost way and form. I can swing in with the Boost.Multiprecision wrapper(s) any time --- even post GSoC '21, as i am getting into a similar time crunch myself.

But the point is full agreement on your plan. Full speed ahead with the details you sketched.

**Comment by ckormanyos** [comment]
Hi @sinandredemption and @cosurgi I am spendin a bit of time getting the CI to _go_ _green_ in the `gsoc2021_double_float` branch. The tests are cycling.

After that (hopefully going green), I'll merge to develop and then we can move forward on separate branch(es) as Fahad has suggested and sketched above.

**Comment by sinandredemption** [comment]
> then we can move forward on separate branch(es) as Fahad has suggested and sketched above.

Thank you @ckormanyos . I have already created a local branch named `gsoc2021_quad_float` on PC, and am working on it.

**Comment by ckormanyos** [comment]
> already created a local branch named `gsoc2021_quad_float` on PC, and am working on it.

Right on!

CI has gone green. So I pushed all that stuff to develop. I ended up retaining the `-2` on the `digits` member of `numeric_limits` and calculated `digits10`and `max_digits10` as suggested by @cosurgi (and old-school Kahan formulae). We need 1 additional bit to pass mul/div tests. So that is done now and all good to go.

Thanks @sinandredemption march on ahead with `quad_float`.

**Comment by ckormanyos** [comment]
The implementation of `numeric_limits` now uses `-2` in the `digits` parameter and derives `digits10` and `max_digits10` from old-school Kahan formulae.

We will close this issue. Furhter progress on potentially using implicit bit(s) will be handled in #26 and possibly other issues.

**Comment by sinandredemption** [comment]
Hello @ckormanyos @cosurgi 

I am reopening this issue to discuss our eccentric usage of `digits` in the `std::numeric_limits<>` specialization of `cpp_double_float` class.

Below I list pros and cons of our definition of `digits`, taking the example of `cpp_double_float<float>` for which `digits == 46` is true.

### Pros
- It reflects the actual accuracy of the `cpp_double_float<>` type, just like `digits10` reflects the number of decimal digits that can be _accurately_ represented by the class.

### Cons
- Usually [am I wrong?], people intuitively use `std::numeric_limits<>::digits` to mean the number of bits in the mantissa of a floating point unit. This, in our case, is still **48** (instead of 46), even though the last 2 bits are not guaranteed to be accurate post-operations.
- @cosurgi has reported exhaustively on the errors he faced after [attempts to reconstruct](https://github.com/BoostGSoC21/multiprecision/commit/766899bb2b05e8f47832d58b99d166913fb496d1#diff-8ce98636352ad37d2f0d1f88c11d031b89c5ca520570fa2db2f5ff520587ddeaR174) a `cpp_double_float` from `digits` number of binary bits.

### Solutions
@cosurgi has proposed the following three possible solutions [in this comment](https://github.com/BoostGSoC21/multiprecision/commit/766899bb2b05e8f47832d58b99d166913fb496d1#commitcomment-54348993):
1. In the `normalize` function make sure that the extra bits which are above `digits` are set to zero.
2. Try if handling implicit bits could help, might be difficult (I believe @cosurgi is will investigate this in #26 ). This might or might not be computationally expensive.
3. Advertise in documentation that the meaning of `digits` is a little sloppy in this type.


 I also propose a fourth hybrid alternative. We could set `digits` to `2 * <digits of underlying type>`, and instead use `epsilon()` to reflect the accuracy of this type. We can then mention or explain all of this specially in the documentation to avoid confusion. Of course, we would have to first check if the the type passes the standard Boost tests without much trouble with the updated value of digits.

Kind regards,
Fahad

**Comment by ckormanyos** [comment]
As long as we clearly publish in documentation the meanings of the members `digits`, `digits10`, `max_digits10`, etc., then I am fine with any solution --- for me, the easier and least run-time-costly the better!

In another post, I wrote somethiong like: Previously extra play digits have successfully been used in Boost.Multiprecision. We handle extra digits within the general description of the so-called _guard_ _digits_ of a floating-point type. Some existing backends, for instance, do actually have more digits internally than those published in the `digits` member of `std::numeric_limits`. The data type, `cpp_dec_float` in particular has rather many (and varying) counts of guard digits.

**Comment by ckormanyos** [comment]
At the end of the day, clients want a well-tested, numerically correct type (within the limits of the type and its implementation/documentation). Most clients do not need a fully scientific breakdown of the intricacies of the limits. So on a practical side, ... working, fast, documented, that's what we need.

**Comment by cosurgi** [comment]
> We could set digits to 2 * <digits of underlying type>, and instead use epsilon() to reflect the accuracy of this type.

Let us try this solution. Maybe it will just work and be simple.

> Try if handling implicit bits could help, might be difficult (I believe @cosurgi is will investigate this in #26)

I realize now this seems tricky. Especially if we prioritize speed. Maybe your solution (`2 * <digits of underlying type>`) will be enough.

> Most clients do not need a fully scientific breakdown

Yes. I'm sorry, I got carried away in the investigations in #57

**Comment by cosurgi** [comment]
I will try to follow @jzmaddock https://github.com/boostorg/multiprecision/pull/249 digits work and implement `2 * <digits of underlying type>` it in the two copies od numeric_limits in our code.

**Comment by cosurgi** [comment]
OK, I added this, if that pipeline passes then I am quite happy with this solution, except for minor points raised in https://github.com/BoostGSoC21/multiprecision/pull/57#issuecomment-892103121

**Comment by cosurgi** [comment]
Fahad, If we base `epsilon()` on the amount of [`guard_bits`](https://github.com/BoostGSoC21/multiprecision/pull/57/files#diff-8ce98636352ad37d2f0d1f88c11d031b89c5ca520570fa2db2f5ff520587ddeaR53) and it will work with the CI tests and other stuff, then I believe that we have a quite elegant and consistent solution to this problem.

**Comment by sinandredemption** [comment]
As reported by @cosurgi [here](https://github.com/BoostGSoC21/multiprecision/issues/26#issuecomment-892111417), the fourth alternative of setting `digits` to the default value while using `epsilon()` to reflect accuracy seems to work fine with CI.

However, I am still concerned that `digits` will be understood by the end-user as the number of accurate bits represented by the type as it is the standard interpretation in Boost libraries.

@cosurgi @ckormanyos I request your thoughts so that we can finally come to consensus on this.

**Comment by ckormanyos** [comment]
>  your thoughts so that we can finally come to consensus on this

If this helps decide, there is a long-standing _history_ surrounding the type `double_double` which was designed toward the end of last century by K. Briggs and refined by Shoup in his NTL early this century. That work wrapped two built-in floating-point elements of type `double` (where these have 8-bytes).

In this historical work, the number of digits was (if I recall correctly) reported to be 104.

I am not sure if my recollection is correct, but, via history and Kahan, this would lead us to the following:

```
   static constexpr int digits       = 2 * (base_class_type::digits - 1);
   static constexpr int digits10     = int(float(digits - 1) * 0.301F);
   static constexpr int max_digits10 = int(float(digits)     * 0.301F) + 2;
```

As long as it makes sense, can be defended and is clearly describable and described in docs, then I would be fine with that.

**Comment by ckormanyos** [comment]
Ooops, I just handled `digits` and the like. As for `epsilon()`, I'm still not sure. Let me take a look at exactly what we did for `cpp_bin_float` already in Multiprecision...

**Comment by ckormanyos** [comment]
According to the _model_ given by `cpp_bin_float`, we would construct (if possible adhering to `constexpr` correctness), the value of `epsilon()`as:

```
epsilon() = ldexp(1, -digits)
```

where the value of `digits` is taken from the deliberations above.

**Comment by jzmaddock** [comment]
This is a whole can of worms, the problem with "double double" and other similar types is that they are potentially discontinuous: which is to say we could have 2*53=106 digits precision, or if the 2 halves of the type aren't contiguous in range, potentially an infinite "precision" (within the limits of their exponent range).  So for example if we cast DBL_MAX and DBL_MIN to a "double double" type and add them together, we get something other than DBL_MAX.  So we have both a maximum and minimum precision depending on circumstance.

Likewise if we take a very strict definition of what epsilon should be according to the std - the smallest number we can add to 1 and effect a change, then it's probably `std::numeric_limits<double>::denorm_min()` !

Unfortunately using definitions/values like these will badly break existing template code, and indeed make it more or less impossible to reason rationally about the behaviour of an algorithm with this type.  So I would say, stick to digits being twice the digits of the base type, and epsilon 2^(1-digits).  That will generally cause fewer headaches for users of the type, though potentially some might still complain ;)

**Comment by jzmaddock** [comment]
>epsilon() = ldexp(1, -digits)

I haven't looked it up to double check, but I'm fairly sure that should be `1-digits`

**Comment by ckormanyos** [comment]
> a whole can of worms, the problem with "double double" and other similar types

We can confirm that comprehending the _proper_ behavior of `double_something` has been challenging/frustrating/etc., for sure. Thanks for the wise words.

> stick to digits being twice the digits of the base type, and epsilon 2^(1-digits). That will generally cause fewer headaches for users of the type

Thank you @jzmaddock with that advice, then, let's summarize in pseudo-code:

```
digits       = 2 * base_class_type::digits;
digits10     = int(float(digits - 1) * 0.301F);
max_digits10 = int(float(digits)     * 0.301F) + 2;
epsilon()    = ldexp(1, 1 - digits);
```

**Comment by ckormanyos** [comment]
> the type double_double which was designed toward the end of last century by K. Briggs and refined by Shoup in his NTL early this century

I was unaware of this, but Shoup still supports `double_double` in the form of his class `quad_float`, as can _finally_ be found at GitHub. There is a beautiful, definitive collection of seemingly field-tested `double-double` algorithms for unary arithmetic [here](https://github.com/libntl/ntl/blob/main/src/quad_float.cpp). Perhaps these can help us straighten out where best to normalize/protect-from-optimize, etc.

**Comment by cosurgi** [comment]
> Thank you @jzmaddock with that advice, then, let's summarize in pseudo-code:

This is similar to my earlier commit e8bf15f

    static constexpr int digits       = 2 * base_class_type::digits;
    static constexpr int digits10     = boost::multiprecision::detail::calc_digits10<digits>::value;
    static constexpr int max_digits10 = boost::multiprecision::detail::calc_max_digits10<digits>::value;

I agree that this configuration causes fewer headaches. We will need to mention some aspects of the "can of worms" in the documentation. Especially the discontinuous nature of this beast, the DBL_MAX + DBL_MIN being a great example.

**Comment by cosurgi** [comment]
Since most of discussion happens here, @sinandredemption I will answer here to [your comment](https://github.com/BoostGSoC21/multiprecision/commit/41bc0686c9cbc37357f42f94fffdf4908fed8247#r54389449).

> Should digits10 reflect the intuitive usage: that is, digits10 represents the number of decimal digits correctly represented by the type (as illustrated in this change)?

Hm, your particular change:

    static constexpr int digits       = 2 * base_class_type::digits;
    static constexpr int digits10     = boost::multiprecision::detail::calc_digits10<digits - 2>::value;
    static constexpr int max_digits10 = boost::multiprecision::detail::calc_max_digits10<digits - 2>::value;

will definitely be breaking the roundtripping. Try it and you will see. We either:

1. use `2 * base_class_type::digits-2` and let `digits10` and `max_digits10` be calculated from it
2. use `2 * base_class_type::digits` and again let other be calculated from it (suggested by John, I tend to agree with that)

But your combination isn't going to work. Maybe I will manage to explain this somehow shortly:

1. log(2)/log(10) ≈ 0.30103 means that one bit is sufficient to determine completely about one third of a decimal digit.
2. log(10)/log(2) ≈ 3.32193 means that one decimal digit determines completely about 3 bits and about a one third of a bit more.

Now let us focus what is the meaning of the last bit: it means that decimals which represent last bit are not "dense" in the sense that (you probably noticed this) all binary → decimal converted number end with "25" or "125". They could never end with "37" or such. So the last decimal digit of `max_digits10` is not "dense" it can only have some values but not the others. And this last decimal digit is necessary to reconstruct back the last bit. But from decimal point of view: the last digit of `max_digits10` is not "dense" so you cannot assign a decimal value (e.g. "7") to it, convert → binary → decimal and expect to have "7" in this place. However you can do it with the last decimal of `digits10`. The "7" will be back where it was. So `max_digits10` is necessary for roundtripping decimal → binary → decimal. But it cannot be relied upon in the mathematical sense of decimal numbers, because number "7" is impossible to put there. Such number can be put at place `digits10` and then roundtripping decimal → binary → decimal on this number will work under condition that roundtripping is done using `max_digits10` and not less.

**Comment by ckormanyos** [comment]
> This is similar to my earlier commit e8bf15f

> I agree that this configuration causes fewer headaches. We will need to mention some aspects of the "can of worms" in the documentation. Especially the discontinuous nature of this beast, the DBL_MAX + DBL_MIN being a great example

OK. Great.

Can we agree on this:

```
static constexpr int digits       = 2 * base_class_type::digits;
static constexpr int digits10     = boost::multiprecision::detail::calc_digits10<digits>::value;
static constexpr int max_digits10 = boost::multiprecision::detail::calc_max_digits10<digits>::value;
```

and also agree on this:

```
epsilon() = ldexp(number<cpp_double_float<T>, ExprTemplates>(1), 1 - digits);
```

**Comment by cosurgi** [comment]
Yes, I have just checked and I agree that `epsilon = ldexp(1  ,  1 - digits )` is the correct value in the sense that `float`, `double`, `long double`, `float128` numbers use it. So this is what most of the algorithms will expect to see in a number and might be designed to rely on it. Hence to minimize headaches we should use it also:

    epsilon() = ldexp(number<cpp_double_float<T>, ExprTemplates>(1), 1 - digits);

**Comment by cosurgi** [comment]
However I am pondering if we should formalize somehow these [guard bits](https://github.com/BoostGSoC21/multiprecision/pull/57/files#diff-8ce98636352ad37d2f0d1f88c11d031b89c5ca520570fa2db2f5ff520587ddeaR62). This is after all what made this [decomposition loop not crashing](https://github.com/BoostGSoC21/multiprecision/pull/57/files#diff-8ce98636352ad37d2f0d1f88c11d031b89c5ca520570fa2db2f5ff520587ddeaR92).

**Comment by cosurgi** [comment]
I have just pushed these values in #57, commit eb4c851b. Please scrutinize it. The other ones still [need to be checked](https://github.com/BoostGSoC21/multiprecision/blob/gsoc2021_double_float_janek/include/boost/multiprecision/cpp_double_float.hpp#L1456) and confirmed.

**Comment by cosurgi** [comment]
@ckormanyos I just noticed however that the pipeline in #57 isn't passing, while it was passing yesterday when I tried this setting for `digits`. Were `test/test_cpp_double_float_arithmetic` somehow disabled earlier, when the pipeline was passing? All this time I thought that these tests were running. Especially the commit 715d3cc passed the CI.

**Comment by sinandredemption** [comment]
I wouldn't be surprised if the practical value of `epsilon()` turned out to be `ldexp(1, 2 - digits)` since the practical precision is two bits less than `2 * <digits of the underlying type>` (as established in the [earlier comments](https://github.com/BoostGSoC21/multiprecision/issues/21#issuecomment-886149087) on this issue).

I guess the way forward would be try using both of the following values:
- `epsilon() == ldexp(1, 1 - digits)`
- `epsilon() == ldexp(1, 2 - digits)`

And observing which one passes the tests.

**Comment by jzmaddock** [comment]
I'm glad to see there's some deep thought going into this, it's pretty darn tricky in this case!

>We either:
>
>    use 2 * base_class_type::digits-2 and let digits10 and max_digits10 be calculated from it
>    use 2 * base_class_type::digits and again let other be calculated from it (suggested by John, I tend to agree with that)

There is one true right answer, it is the largest value for B, where we are able to represent every possible bit combination of a B-bit floating point number in our type.  The only wrinkle I see is that the first bit of each "limb" in the "double double" is implicit and not actually stored.  However, I don't think that changes anything - if the first bit after the end of the first "limb" is a zero, then we just reduce the exponent of the second limb until it's implicit first 1 bit lines up with the next 1 bit in our B bit number.  So I still think it's 2 * base_class_type::digits.

With regard to digits10 and max_digits10, these also have clear definitions (though that doesn't mean they're easy to work out!).

digits10 is the number of digits in a decimal number that can be stored in our type, in other words digits10 guarantees decimal->binary->decimal round tripping.

max_digits10 is the reverse of this, and is the number of decimal digits we need to create in order to guarantee binary->decimal->binary round tripping.  BUT, we have a  big issue caused by the non-contiguous nature of the number - think about how many decimal places will be required to round trip DBL_MAX + DBL_MIN for example.  We can figure out how many digits that is from the min/max exponents, but it's going to be a lot!  Even more so if we instantiate the template on say __float128 to get the extended exponent range.

**Comment by cosurgi** [comment]
> @ckormanyos I just noticed however that the pipeline in #57 isn't passing, while it was passing yesterday

> I guess the way forward would be try using both of the following values:
>    `epsilon() == ldexp(1, 1 - digits)`
>    `epsilon() == ldexp(1, 2 - digits)`
> And observing which one passes the tests.

OK. I know why it stopped passing the CI pipeline - the recent changes in branch develop are responsible. I am halfway in fixing this. I am currently running 2e7 tests on a modified `epsilon` values for each of these tests: `add` `sub` `mul` `div` `sqrt` in file `./test/test_cpp_double_float_arithmetic.cpp`. The current (being tested right now) values are:

* `add` uses `ldexp(1 , 2 - digits )`
* `sub` uses `ldexp(1 , 2 - digits )`
* `mul` uses `ldexp(1 , 4 - digits )`
* `div` uses `ldexp(1 , 3 - digits )`
* `sqrt` uses `ldexp(1 , 3 - digits )`

Now the question is: does it mean that we should use `epsilon() == ldexp(1, 4 - digits)` or stay with `epsilon() == ldexp(1, 1 - digits)` and write in documentation about each math operation producing different error. Honestly I don't know which is better. I slightly prefer `ldexp(1 , 4 - digits )` as that is what we can guarantee for all of the checks to remain correct.

**Comment by sinandredemption** [comment]
@cosurgi Doesn't the `develop` branch currently effectively use `epsilon() = ldexpr(1, 2 - digits)` (see [this](https://github.com/BoostGSoC21/multiprecision/blob/e1247cce7464d807b06426f9f9b92f1df6db880c/include/boost/multiprecision/cpp_double_float.hpp#L1469)) while [passing all the tests](https://github.com/BoostGSoC21/multiprecision/actions/runs/1090576586)?

**Comment by ckormanyos** [comment]
> I don't know which is better. I slightly prefer `ldexp(1 , 4 - digits)` as that is what we can guarantee for all of the checks to remain correct

I share your confusion. Please note that develop does pass those tests as they are written and passed in develop. Subjectively, I got the impression that develop is passing the tests with slightly fewer guard digits. But this depende on exactly _how_ we end up setting the value of `digits`. I'm still not quite sure we have the best possible algorithms for add/sub/mul/div. But this might be a subjective impression.

**Comment by cosurgi** [comment]
There are custom values which are pushing the limits:

* [add](https://github.com/BoostGSoC21/multiprecision/blob/e1247cce7464d807b06426f9f9b92f1df6db880c/test/test_cpp_double_float_arithmetic.cpp#L166)
* [sub](https://github.com/BoostGSoC21/multiprecision/blob/e1247cce7464d807b06426f9f9b92f1df6db880c/test/test_cpp_double_float_arithmetic.cpp#L199)
* [mul](https://github.com/BoostGSoC21/multiprecision/blob/e1247cce7464d807b06426f9f9b92f1df6db880c/test/test_cpp_double_float_arithmetic.cpp#L232)
* [div](https://github.com/BoostGSoC21/multiprecision/blob/e1247cce7464d807b06426f9f9b92f1df6db880c/test/test_cpp_double_float_arithmetic.cpp#L265)
* [sqrt](https://github.com/BoostGSoC21/multiprecision/blob/e1247cce7464d807b06426f9f9b92f1df6db880c/test/test_cpp_double_float_arithmetic.cpp#L298)

My local tests will be finished soon, then I will push the new values which push the test limits.

**Comment by ckormanyos** [comment]
> there are custom values which are pushing the limits:

Yes Janek, I wanted to mention that. I made sure that the different operators can set different thresholds. I am also uncertain if the actual test method in that file is, let's say, _fair_. That motivated me to write #59

@cosurgi if you find anything out like your branch passes with lower tolerance thresholds than develop or vice-versa, I would like to find that out.

**Comment by cosurgi** [comment]
@ckormanyos I pushed latest changes in my branch (also I have rebased on develop). The `float128` tests are still hammering 2e7 tests. But others have passed, so it seems that I **lowered your limit by one for div** others are exactly the same as yours, except for the extra "2" added to each, which comes from our preferred value of `digits` (larger by 2).

* `add` uses `ldexp(1 , 2 - digits )`
* `sub` uses `ldexp(1 , 2 - digits )`
* `mul` uses `ldexp(1 , 4 - digits )`
* `div` uses `ldexp(1 , 3 - digits )`
* `sqrt` uses `ldexp(1 , 3 - digits )`

**Comment by ckormanyos** [comment]
> @ckormanyos I pushed latest changes in my branch (also I have rebased on develop). The `float128` tests are still hammering 2e7 tests. But others have passed, so it seems that I **lowered your limit by one for div** others are exactly the same as yours, except for the extra "2" added to each, which comes from our preferred value of `digits` (larger by 2).

Thank you, Janke, for working so hard on this. Thanks for these results and a great report, @cosurgi.

Is this work reflected in your branch? Then we should push to develop after re-adjusting the tests.

Usually in these situations (when potentially wily edge cases are around), I use several techniques. One of them is to setup a _night_ _build_ on GHA using a moderate number of test cases (like 50k or 100k in our case). I seed the string generator(s) with _different_ random seed(s) based on `std::clock()` or a `<chrono>` time stamp so that different tests run each nightly and on each virtual machine in the server farm. Then I capture any potentially found outliers. In this case, a raw hex dump might be best.

Let's get your cool new stuff into develop. I will setup a night build. After that, I'll put in some diagnostic print(s) for catching any potential outliers that might arise.

@sinandredemption let's move forward now consequently with the same drive toward numerical correctness on `cpp_quad_float`. After merging JaneK's stuff into develop, how can we best move forward on Boost-ifying your quad stuff?

**Comment by sinandredemption** [comment]
> how can we best move forward on Boost-ifying your quad stuff?

I think all the Boost routines will just be quad-adapted version of `cpp_double_float<>` routines on which you have worked on amazingly well.

One question: apologies if I am a bit out of the loop, but as I mentioned in [this comment](https://github.com/BoostGSoC21/multiprecision/issues/21#issuecomment-892940024), why exactly are we increasing the value of `epsilon()` to `ldexp(1, 4 - digits)` when apparently all (or most) of the tests did pass well with [the earlier value](https://github.com/BoostGSoC21/multiprecision/blob/e1247cce7464d807b06426f9f9b92f1df6db880c/include/boost/multiprecision/cpp_double_float.hpp#L1469)? Is it related to the failing test cases that [you had mentioned](https://github.com/BoostGSoC21/multiprecision/issues/21#issuecomment-885631553) before?

@ckormanyos

**Comment by cosurgi** [comment]
> Is this work reflected in your branch?

Yes it's ready to merge. And I see you have merged this already :)

> different random seed(s) based on std::clock() or a <chrono> time stamp

Yes. Extending these decompostion / rebuild tests with random numbers is the obvious next step. Currently it's just a few (always the same) cases. I feel that random numbers will find more problems there. I feel that we will need to extract `local::control::get_random_fixed_string` to some common header for this.

> why exactly are we increasing the value of epsilon() to ldexp(1, 4 - digits) when apparently all (or most) of the tests did pass well with the earlier value?

That earlier value wasn't used in the tests. The epsilon values were [chosen specific](https://github.com/BoostGSoC21/multiprecision/issues/21#issuecomment-892957211) for each test using ldexp calculation, instead of using epsilon.

**Comment by ckormanyos** [comment]
>> Is this work reflected in your branch?

> Yes it's ready to merge. And I see you have merged this already

Yes, @cosurgi I really went progressively forward on your PR, hoping it was merge-ready. To me, everything looks good.

If we need to tune/correct a thing or two moving forward, I'm OK with that.

Cc: @sinandredemption
